apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-paradox
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: helm
    repoURL: https://github.com/vfarcic/devops-paradox.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        ingress:
          #host: devopsparadox.com
          host: devopsparadox.192.168.1.8.nip.io
      version: v3
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
